### ISSUE TITLE
No nightly reboot warning

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#121]
There are no in-game server shutdown warnings before the nightly reboot.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
In my point of view, if it's not present on SB, it's the case for all servers, so we need to fix this for all servers

**Comment by Lymkwi** [comment]
> In my point of view, if it's not present on SB, it's the case for all servers, so we need to fix this for all servers

Smart deduction sherlock.
I'll investigate that; it's also possible that the message isn't seen because players are kicked immediately. Anyway, I'll post my results when I'm done.

**Comment by Lymkwi** [comment]
Here it was : the function giving us a string representing the hour always returned a string with two digits, but we always tested "4" instead of "04".
Fixed on all servers, need a merge ASAP.
https://github.com/MinetestForFun/server-minetestforfun/commit/6387a54bb767ff947bc7fcde7c7f6fd6908bbe01
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/43d0ef3efda601af8c997456daf5d2f7b3c72b25
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/879be0d1a9ad514a22844934658dd3b3b2e4e64a
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/f0353dc8c1221567349a156597e43bc4a5a585ba

**Comment by BetterToAutomateTheWorld** [comment]
Ok thank you for the fix, i will merge this evening
