### ISSUE TITLE
lag and fps drop due to chopped trees dropping leaves

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#138]
If i chop more than 2 or 3 trees i get a huge pile of dropped leaves that just kills performance and generates lag. If i chop 20+ trees it gets crazy.

Can this be changed back to leaves disappear like before?

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Lag in your side (only you), not lag in the server side (for all players)

We did this tweak because we want to avoid server lag. (for all players)

In my point of view, we won't/can't change this until it's needed...

**I let this issue open for a short amount of time, if someone else have an idea**

**Comment by Lymkwi** [comment]
I'll change the code (or the config key I think) ~~to send leaves directly into the player's inventory, or drop them in case there's not enough room. It's easier that way.~~ (too hard)
I'll change the code to not drop leaves. If players want them, they will have to dig them before removing the trunk.

**Comment by BetterToAutomateTheWorld** [comment]
drop leaves directly to the player inventory is something we spoke about and yes it was too hard...

For your commit / solution, good idea @LeMagnesium ,I didn't think about it !

**Comment by Lymkwi** [comment]
Is it merged yet?

**Comment by BetterToAutomateTheWorld** [comment]
Not yet merged
