### ISSUE TITLE
Problem with infinite water quest

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#225]
Numerous players have reported issues completing the water quest, and i have witnessed the issue myself. It seems making a 2x2 hole doesn't work, but usually a bigger one (3x3 or 4x4) will trigger the quest. 

Edit: It now seems maybe the direction of the diagonal could be the trigger?

Could this be related to the 4.16 update?
:large_orange_diamond:

**Comment by Lymkwi** [comment]
I think I know why that one isn't working. The issue simply is that skyblock doesn't check in a plus pattern, but a cross pattern, because it assumes we will place our source diagonally to make infinite ones. However, many players will put it in a plus (2 nodes apart) and get the central source.
I'll fix it.

**Comment by aerozoic** [comment]
I personally witnessed players trying to complete the quest. They were placing diagonal. It was the direction that caused issues. (e.g. going from top left to bottom right instead of bottom left to top right.) I'm not sure which direction actually triggered, but that was the issue.
🔶

**Comment by Lymkwi** [comment]
It was just a case of badly handled edge cases anyways
