### ISSUE TITLE
Server Crash!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#227]
Any player can crash the server simply by giving the command "/last-login playername random text that is long enough to trigger the error".

And the error from the logs:
```
2017-07-29 16:14:55: ERROR[Main]: ServerError: Lua: Runtime error from mod '*builtin*' in callback on_chat_message(): .../minetestforfun_skyblock/mods/mysql_auth/mysql/mysql.lua:1178: string too long
```
@ElementW ping because it's mysql.

Thanks to @YuGiOhJCJ for the report.
:large_orange_diamond:

**Comment by aerozoic** [comment]
Was this fixed?
:large_orange_diamond:

**Comment by YuGiOhJCJ** [comment]
No it is not fixed, I have just did the test and there is still a server crash when I type the command.

**Comment by ElementW** [comment]
My local tests show max allowed string length is 32, which turns out to be the max username length. I'll fix that as part of my local changes, but getting things upstream will be a bit trickier since I've split `mysql_auth` into another `mysql_base` mod requiring additional conifg. @Darcidride must just be aware of that.

**Comment by ElementW** [comment]
[Fixed](https://github.com/MinetestForFun/mysql_auth/commit/67dc261bd0e9679b01bae1854218cb442724b979#diff-d7d74284e2e39f6c06d199c8e2bedbd0R151). Note this must be merged to `master` and then to the server before taking effect.

**Comment by BetterToAutomateTheWorld** [comment]
The server will be merged soon with the repository version
Thank you for your work @ElementW
