### ISSUE TITLE
minetestforfun-skyblock's server has been down for quite a while now

### ISSUE THREAD

**Issue by arielenter** [MinetestForFun/server-minetestforfun-skyblock#232]
The server has been down since last weekend. It may have been down even before that. Is everything all right? Also I couldn't connect to the IRC at daconcepts.com 

Anyway, I hope the server will be back soon.  Thank you.

**Comment by aerozoic** [comment]
The exact cause of the server shutdown is still unknown and unfortunately the owner has just been too busy to troubleshoot the issue. I do hope it will be back online soon though when he gets time to fix it! 

Also the IRC server (inchranet) is shutdown but that is completely unrelated and separate from the Minetestforfun team.

This issue is directly related to #231 so i'm going to close this one and we can discuss it further in that issue.
:large_orange_diamond:
