### ISSUE TITLE
Cardinal points teleports.

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#47]
I have been talking to one of the admins about teleports. Helping new players gets tedious and takes more time as their homes are being place further and further, so he suggested that a spawnpoint in the middle would be helpful. And yes it would be.

But, since the world wraps around the center with every new player in a square-like shape, then maybe it would be a good idea to place spawn points on each side of the world. Using the world map would be easy to stablish the cardinal points and from in-game all that needs to be done is look the trayectory of the sun/moon to locate est and west. So it won't be that confusing. Plus, this spawns could carry a marker, just like a player's tag that can be seen all through the map.

I assume this would be usable from lvl 3 and on.

**Comment by Lymkwi** [comment]
The fact is that we already have a teleportation mod installed, `travelpoints`, and placing standard teleportation stations would even be easier using the `warp` mod. However, as I recall, players can, on skyblock, have unlimited use of their `home` and `sethome` functions.
@Ombridride is probably the only person able to place and set fixed warp points on the map so his opinion here is important. My opinion is that a mod like warp would be more suitable than travelpoints, which players can also create (as far as I remember).
Also, restraining the use of a feature to players under a certain level is a pain to code, it would be easier if everybody could use them, considering everybody can already use `/home`.

**Comment by BetterToAutomateTheWorld** [comment]
The idea is to grant the players the possibility to craft and put/use warp teleporters when they reach the level 5, it's a level 5 privilege ;)

Need @gravgun for a more accurate answer

**Comment by Lymkwi** [comment]
Allowing players to craft/place warps is a bad idea for me, unless there are restrictions on the amount placed, but having publicly accessible and usable warps like on the Classic server would be okay.

**Comment by ElementW** [comment]
@Ombridride See @LeMagnesium's comment about travel pads.
It'd easily get out of hand, _somehow_.

`travelpoints` has a system that separates personal and global travelpoints, no issue there. Only the ones with the good privs can get their personal TPs global by the click of a button.

What I'm more concerned about though is sort of "abuse" or "over-use" to the least. Also a sense of uselessness there; level 4 players have fly and fast.

Also, performance-wise, and, guess what, due to Minetest's bullshit internal design and dev mindset, travelpoints are costly. MT doesn't provide any method to have a callback called upon node contact, so `travelpoints`, which teleports players as soon as they stand on the pads, has to periodically check whether players are standing on TP pads, using an ABM. ABMs have awful performance (and to be reasonably responsive, the mod has a 1 second tick rate, which for an ABM is fast).
Letting people place as many as they want may lead to server performance doom.

We're an active community, we easily get to see that people want a warp from X to Y. I think only we should be able to create teleport pads.

**However** this is about travel **pads**, not travel **points**, which fortunately are handled separately in terms of player privs.

Travel points are usable using commands (when you have the `travelpoints` priv), and as such is a completely passive system, so isn't disruptive in any way. Letting level 5+ players using it is a reasonable decision.

As however travelpoints aren't supposed to be an integral part of our customized Skyblock's questline, no tutorials will be made, just a mention of priv giving, and the list of commands it allows players to use (along with a "use the /help "<command>" command to know how they work" line).

**Conclusion**:
- Let level 5+ players have the `travelpoints` priv and use the commands
- Only let the MFF team the use of the `tpglobal` (set/drop global TPs) and `travelpads` (placing pads) privs

**Comment by rredesigns** [comment]
Sounds promising. I hope you implement lvl5 soon then. :dancer:

**Comment by BetterToAutomateTheWorld** [comment]
@gravgun some other mods do the same things as travelpoints and has no UGLY ABMs

So, _travelpoints_ (for players) or _warp crystals_ (only moderators/administrators use) are better... 

In my point of view, a way that players can put they own teleporters is better

**Comment by rredesigns** [comment]
What about travelnet boxes for lvl4 untill you get to implement lvl5? As I read, it is very efficient in performance terms because it depends on user input.

**Comment by BetterToAutomateTheWorld** [comment]
Travelnet boxes and the spawnpoint are now added, I think it's enough for your travels :)

But, Can @gravgun give me more informations about the Travelnet boxes : when players will be able to craft/use them ? in which level ? A quest to craft/put/use them will be aded to introduce them ? The texture is over or not ?

i know, for the moment everybody can craft/put/use them at any times, but the final point isn't this. Im ok with the fact of players can use them at any time, but not craft/put them, we need a level quests for this kind of think in my point of view, maybe a level 5 or 6 goal ?

**Comment by ElementW** [comment]
Drop the travelpoints already. Travelnet boxes are more efficient and don't have any ABMs.

**Comment by BetterToAutomateTheWorld** [comment]
^ Yes, just a mistake, i edited my previously questions with Travelnet boxes words ^

**Comment by ElementW** [comment]
With the updated wording: Craft and use from level 1, since I don't want to go dig in the code to deny usage, nor can we even restrict crafting.
Placing them should be restricted to level... welp there's already a restriction: you need mese to craft travelboxes and you get mese on Level 3 IIRC. But yea forcing Level 5 or 6 to place them would limit their number.

**Comment by BetterToAutomateTheWorld** [comment]
I agree with you, the craft recipe should be always available for show new players it's possible to craft/use them.
However, level 5 or 6 it's a good idea, if i can add something : if a player without the level quest completed try to put a "travelnet box", send him a chat message to explain why he can't do this for the moment

**Comment by BetterToAutomateTheWorld** [comment]
Issue rejected, now travelpoint and /spawn and /home, it's enough.

**Comment by cessna151** [comment]
I believe this issue has been fully addressed. If not reopen it.

**Comment by aerozoic** [comment]
Edit, @Ombridride beat me to it :D
