### ISSUE TITLE
in game /ignore feature 

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#56]
Let's discuss adding a /ignore <playername> command. Questions, concerns, comments?

**Comment by rredesigns** [comment]
Could easily be achieved with Chat Plus mod. It is needed at this point, that we have many more people playing.

**Comment by ObaniGemini** [comment]
I think there should be a message like " xplayer is ignoring you" when a player is ignored by another. This would minimize spam/flood a little bit (IMO). But a chat message would probably be ignored as well, so maybe a top-right message (with some flashy color ?)?

**Comment by BetterToAutomateTheWorld** [comment]
The chatplus mod won't be added, we met some problems with it, but we can code this feature in the skyblock subgame if it's needed

For example, **Kevin** blacklist **BadGuy** :
- If **BadGuy** speaks on the public chat, **Kevin** can't see it.
- If **BadGuy** sends a mail or a msg to **Kevin**, **Kevin** can't see/receive it and in this case, a small message is displayed in the **BadGuy** chat to inform him **Kevin** blacklist/ignore him.

Also, a small GUI to add/delete people(s) from the "blacklisted names" should be great. (with maybe a counter next to the blacklisted names with an "ignored messages from this people counter feature", just for information and a proof of the ignored feature works well and help you keeping your chat/inbox clean)

This kind of work seems good to me. 
Need other opinions/comments, nobody is perfect, I surely missed some cases ! :)

**Comment by rredesigns** [comment]
I thing the GUI is a bit too much for a case when only 2 commands are needed. /ignore and /unignore are easy enough for anyone to use, plus, it won't be used intensively to justify it, or I hope so. :D

**Comment by BetterToAutomateTheWorld** [comment]
With our previous experiences, i can say, it's always better for noob players when you can give them a GUI :)
but yes the command is simple to use, you will can use it instead of the GUI if you want

**Comment by aerozoic** [comment]
I like Obani's suggestion, a notification that you have been ignored would be helpful. 

Also here is a list of commands that i think would be useful:

/ignore playername - Ignores player
/unignore playername - Unignores player
/ignore_list - Shows a list of all players i have ignored
/ignoreme_list - Shows a list of all players that have ignored me
/unignore_all - Unignores all players on my ignore list
/ignore_chat - Disables chat but still allows built-in game messages like completed quest messages, unlike F2 which disables all messages including built-in game message
/unignore_chat - Enables chat

**Comment by Lymkwi** [comment]
Actually, any kind of modification of the chat's behavior is made painful and imprecise because of the engine. The only way to achieve what you ask for is reproducing exactly what chatplus did, and it includes part of the code's behavior that bothered us so much that we finally removed it. The mechanism I'm talking about is a loop called by the `on_chatmessage` callback, which would take upon the task of sending every player the messages and filter them according to ignore lists. The problem though is that the only way to replace the engine's response to chat message (sending them to everyone) is making our callback function the last one to be called. But then, there will be no track of the chat in the server's logs, there will hypothetically no message sent to irc : if a mod makes a callback function the last one to be called, and by that I mean the one blocking the engine's response and the other callback functions, it risks shutting down other mod's systems.
I'm aware ignore is a really interesting feature, but considering how MT and its callback system is designed, it's just a big pain to code and a potential source of bugs whenever mods are added/removed.
(I'll see if I can find a workaround but I don't promise anything)

**Comment by Lymkwi** [comment]
There you have it : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/35556a5e05e148a7e7499f9e6bbc5004746cfcef

**Comment by BetterToAutomateTheWorld** [comment]
Good job !
The inventory button and GUI are missing, but for a beginning it's really great :)

**Comment by aerozoic** [comment]
I think it's fantastic!

**Comment by aerozoic** [comment]
Is it possible to have a command to check if somebody has ignored you or show a list of people that ignored you; either way? And/or make it so nobody can ignore a moderator?  :large_orange_diamond:

**Comment by rredesigns** [comment]
cessna, you ask too much. Plus, there's no need for that. |¬¬'|

**Comment by BetterToAutomateTheWorld** [comment]
When you will send a /msg /mail to a player that ignore you, you will see a message which told you this player ignore you, in my point of view it's enough, but maybe @LeMagnesium will be interested in adding this feature, wait for his answer :)

**Comment by Lymkwi** [comment]
There. Both points [implemented](https://github.com/MinetestForFun/ignore/commit/22d0e53dfa726158aaefe5344ffa31a3f06a8e4b) : 

> - Add a subcommand to check whether or not a player is ignoring you
> - Add the ignore_protection privilege. Players with that privilege cannot be ignored

**Comment by aerozoic** [comment]
Excellent work @LeMagnesium!
