### ISSUE TITLE
Momentary server freeze on new player join.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#80]
I noticed today several times when a new player joins, the server will freeze for 5-10 seconds and it's not lag, i checked :smile:  @LeMagnesium it was suggested by @Ombridride that this might be due to your code checking for unprotected spawn points.  :small_orange_diamond:

**Comment by Lymkwi** [comment]
This lag is most likely due to the server cycling through available spawn positions and checking the vicinity for both protection areas and nodes other than air. Sadly, this process takes long, but needs to be done entirely in order to protect already existing buildings and protected areas. This commit adds the code responsible for this : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/b0abd39c6c88d815a517c3935c6855c25f1d4836.
You can only blame protector's check system and minetest for this, and maybe also people building large buildings over unused space. There is no way to fix this.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, I think me can't solve it...

You can close the issue @LeMagnesium
